name: IC

on:
  pull_request:
    branches: [main]

jobs:
  check:
    name: Vérifier la synchronisation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.12"

      - name: Installer ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Installer just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0

      - name: Synchroniser et vérifier
        run: just sync && just check
